# Acceder a los elementos del Array.

### Array dimensional 

In [ ]:
## Crear un array unidimensional
import numpy
array_uni = np.array([1,3,5,7,9])
print("Saper: ", array_uni.shape)
print("array_uni: ", array_unit)

In [ ]:
#Acceder al 5 elemento del Array 
array_uni[4]


In [ ]:
# Acceder al tercer elementon del array
arrays([2:4])

In [ ]:
#Acceder a los elementos del array 0,3 y 5
array_uni([0::2])

## Array multidimensional


In [ ]:
# Crear un Array Multidimensional
import numpy
array_multi = np.array([1,2,3,4],[5,6,7,8])
print ("Shape: ", array_multi.shape)
print ("Array_multi: ", array_multi)

In [ ]:
# Acceder al cuarto elemento del Array_multi
array_multi[0, 3]


In [ ]:
# Acceder a la segunda fila del Array
array_multi[1, :]

In [ ]:
# Acceder al tercer elemento de las 2 dimensiones
array_milti[0:2,2]

# Modificacion del Array 

In [ ]:
# Crear un array unidimensional e iniciarlo  con el rango de elementos del 0 al 27
array1 = np.arange(28)
print ("Shape: ", array1.shape)
print ("Array1: ", array1)

In [ ]:
# Cambiar las dimensiones del Array y sus longitudes.
array1.shape = (7,4)
print ("Shape: ", array1.shape)
print ("Array1: ", array1)

In [ ]:
# pi= el ejemplo anterior devuelve un array que apunta alos mismos datos.
# importancia:Las modificaciones en un array , modifican el otro array
array2 = array1.reshape(4,7)
print ("Shape: ", array2.shape)
print ("Array2: ", array2)

In [ ]:
# MOdificar el nuevo arreglo 
array2[0,3]=20
array2("Array 2: \n", array2)

In [ ]:
print("Array1: \n", array1)

In [ ]:
# REgresar el array a su estado original 
# NOtra: El numero array apunta a los mismo datos.
print("Array1:\n", array1.ravel())

## Operaciones arirmeticas con Arrays

In [ ]:
#Crear un array unidimensional
array1 = np.arange (1,18,2)
array2 = np.arange(5)
print("Array 1:", array1)
print("Array 2:", array2)


In [ ]:
#suma
print(array1 + array2)

In [ ]:
#Resta
print(array1 - array2)


In [ ]:
#Multiplicacion 
#nota: NO es una multiplicacion de matrices de matrices
print(array1 * array2)

## Broadcasting 

In [3]:
# si se aplican operaciones aritmeticas sobre array que
#no tienen la misma forma (shape), NUmpy aplican ugna propiedad
#que se les conoce como Broadcastin

In [10]:
#Crear dos array UniDImensionales
import numpy as np
array1 = np.arange(5)
array2 = np.a([3])
print ("Shape Array 1:", array1.shape)
print ("Array 1:", array1)
print()
print ("Shape Array 2:", array2.shape)
print ("Array 2:", array2)

Shape Array 1: (5,)
Array 1: [0 1 2 3 4]

Shape Array 2: (1,)
Array 2: [3]


In [11]:
#Suma de ambos arrays
array1 + array2

array([3, 4, 5, 6, 7])

In [13]:
#Crear dos arreglos MultiDimensional y UniDImensinal
array1=np.arange(6)
array1.shape=(2, 3)
array2=np.arange(6,18,4)
print ("Shape Array 1:", array1.shape)
print ("Array 1:", array1)
print()
print ("Shape Array 2:", array2.shape)
print ("Array 2:", array2)

Shape Array 1: (2, 3)
Array 1: [[0 1 2]
 [3 4 5]]

Shape Array 2: (3,)
Array 2: [ 6 10 14]


In [14]:
#SUma
array1 + array2

array([[ 6, 11, 16],
       [ 9, 14, 19]])

## Funciones estadisticas sobre Arrays .

In [17]:
# Creacion de un Array unidimensional 
array1 = np.arange(2,18,2)
print("Array 1:", array1)

Array 1: [ 2  4  6  8 10 12 14 16]


In [18]:
#media
array1.mean()

9.0

In [19]:
#Suma de los elementos del array.
array1.sum()

72

## Funciones universales eficientes proporcionadas por Numpy:**Ufunc.



In [20]:
# Cuadrado de los elementos del array
np.square(array1)

array([  4,  16,  36,  64, 100, 144, 196, 256])

In [21]:
#Raiz cuadrada de los elementos del array
np.sqrt(array1)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766,
       3.46410162, 3.74165739, 4.        ])

In [22]:
#Exponencial de los elementos del array
np.exp(array1)

array([7.38905610e+00, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03,
       2.20264658e+04, 1.62754791e+05, 1.20260428e+06, 8.88611052e+06])

In [23]:
#logaritmo natural de los elementos del array
np.log(array1)

array([0.69314718, 1.38629436, 1.79175947, 2.07944154, 2.30258509,
       2.48490665, 2.63905733, 2.77258872])